// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/DeviceRPC/decryptiondevice.proto

package io.grpc.decryptiondevice;

/**
 * <pre>
 * Decryption Request
 * - Byte array containing ciphertext
 * - Proofs represented as JSON trees
 * </pre>
 *
 * Protobuf type {@code decryptiondevice.DecryptionRequest}
 */
public  final class DecryptionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:decryptiondevice.DecryptionRequest)
    DecryptionRequestOrBuilder {
  // Use DecryptionRequest.newBuilder() to construct.
  private DecryptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DecryptionRequest() {
    ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    proofOfPresence_ = "";
    proofOfExtension_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DecryptionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            ciphertext_ = input.readBytes();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            proofOfPresence_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            proofOfExtension_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_DecryptionRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_DecryptionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.decryptiondevice.DecryptionRequest.class, io.grpc.decryptiondevice.DecryptionRequest.Builder.class);
  }

  public static final int CIPHERTEXT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString ciphertext_;
  /**
   * <code>bytes ciphertext = 1;</code>
   */
  public com.google.protobuf.ByteString getCiphertext() {
    return ciphertext_;
  }

  public static final int PROOFOFPRESENCE_FIELD_NUMBER = 2;
  private volatile java.lang.Object proofOfPresence_;
  /**
   * <code>string proofOfPresence = 2;</code>
   */
  public java.lang.String getProofOfPresence() {
    java.lang.Object ref = proofOfPresence_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proofOfPresence_ = s;
      return s;
    }
  }
  /**
   * <code>string proofOfPresence = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProofOfPresenceBytes() {
    java.lang.Object ref = proofOfPresence_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proofOfPresence_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROOFOFEXTENSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object proofOfExtension_;
  /**
   * <code>string proofOfExtension = 3;</code>
   */
  public java.lang.String getProofOfExtension() {
    java.lang.Object ref = proofOfExtension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proofOfExtension_ = s;
      return s;
    }
  }
  /**
   * <code>string proofOfExtension = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProofOfExtensionBytes() {
    java.lang.Object ref = proofOfExtension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proofOfExtension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!ciphertext_.isEmpty()) {
      output.writeBytes(1, ciphertext_);
    }
    if (!getProofOfPresenceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, proofOfPresence_);
    }
    if (!getProofOfExtensionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, proofOfExtension_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!ciphertext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, ciphertext_);
    }
    if (!getProofOfPresenceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, proofOfPresence_);
    }
    if (!getProofOfExtensionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, proofOfExtension_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.decryptiondevice.DecryptionRequest)) {
      return super.equals(obj);
    }
    io.grpc.decryptiondevice.DecryptionRequest other = (io.grpc.decryptiondevice.DecryptionRequest) obj;

    boolean result = true;
    result = result && getCiphertext()
        .equals(other.getCiphertext());
    result = result && getProofOfPresence()
        .equals(other.getProofOfPresence());
    result = result && getProofOfExtension()
        .equals(other.getProofOfExtension());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCiphertext().hashCode();
    hash = (37 * hash) + PROOFOFPRESENCE_FIELD_NUMBER;
    hash = (53 * hash) + getProofOfPresence().hashCode();
    hash = (37 * hash) + PROOFOFEXTENSION_FIELD_NUMBER;
    hash = (53 * hash) + getProofOfExtension().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.DecryptionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.decryptiondevice.DecryptionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Decryption Request
   * - Byte array containing ciphertext
   * - Proofs represented as JSON trees
   * </pre>
   *
   * Protobuf type {@code decryptiondevice.DecryptionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:decryptiondevice.DecryptionRequest)
      io.grpc.decryptiondevice.DecryptionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_DecryptionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_DecryptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.decryptiondevice.DecryptionRequest.class, io.grpc.decryptiondevice.DecryptionRequest.Builder.class);
    }

    // Construct using io.grpc.decryptiondevice.DecryptionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;

      proofOfPresence_ = "";

      proofOfExtension_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_DecryptionRequest_descriptor;
    }

    public io.grpc.decryptiondevice.DecryptionRequest getDefaultInstanceForType() {
      return io.grpc.decryptiondevice.DecryptionRequest.getDefaultInstance();
    }

    public io.grpc.decryptiondevice.DecryptionRequest build() {
      io.grpc.decryptiondevice.DecryptionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.decryptiondevice.DecryptionRequest buildPartial() {
      io.grpc.decryptiondevice.DecryptionRequest result = new io.grpc.decryptiondevice.DecryptionRequest(this);
      result.ciphertext_ = ciphertext_;
      result.proofOfPresence_ = proofOfPresence_;
      result.proofOfExtension_ = proofOfExtension_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.decryptiondevice.DecryptionRequest) {
        return mergeFrom((io.grpc.decryptiondevice.DecryptionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.decryptiondevice.DecryptionRequest other) {
      if (other == io.grpc.decryptiondevice.DecryptionRequest.getDefaultInstance()) return this;
      if (other.getCiphertext() != com.google.protobuf.ByteString.EMPTY) {
        setCiphertext(other.getCiphertext());
      }
      if (!other.getProofOfPresence().isEmpty()) {
        proofOfPresence_ = other.proofOfPresence_;
        onChanged();
      }
      if (!other.getProofOfExtension().isEmpty()) {
        proofOfExtension_ = other.proofOfExtension_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.decryptiondevice.DecryptionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.decryptiondevice.DecryptionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ciphertext = 1;</code>
     */
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    /**
     * <code>bytes ciphertext = 1;</code>
     */
    public Builder setCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ciphertext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes ciphertext = 1;</code>
     */
    public Builder clearCiphertext() {
      
      ciphertext_ = getDefaultInstance().getCiphertext();
      onChanged();
      return this;
    }

    private java.lang.Object proofOfPresence_ = "";
    /**
     * <code>string proofOfPresence = 2;</code>
     */
    public java.lang.String getProofOfPresence() {
      java.lang.Object ref = proofOfPresence_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proofOfPresence_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proofOfPresence = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProofOfPresenceBytes() {
      java.lang.Object ref = proofOfPresence_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proofOfPresence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proofOfPresence = 2;</code>
     */
    public Builder setProofOfPresence(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proofOfPresence_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proofOfPresence = 2;</code>
     */
    public Builder clearProofOfPresence() {
      
      proofOfPresence_ = getDefaultInstance().getProofOfPresence();
      onChanged();
      return this;
    }
    /**
     * <code>string proofOfPresence = 2;</code>
     */
    public Builder setProofOfPresenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      proofOfPresence_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object proofOfExtension_ = "";
    /**
     * <code>string proofOfExtension = 3;</code>
     */
    public java.lang.String getProofOfExtension() {
      java.lang.Object ref = proofOfExtension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proofOfExtension_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proofOfExtension = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProofOfExtensionBytes() {
      java.lang.Object ref = proofOfExtension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proofOfExtension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proofOfExtension = 3;</code>
     */
    public Builder setProofOfExtension(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proofOfExtension_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proofOfExtension = 3;</code>
     */
    public Builder clearProofOfExtension() {
      
      proofOfExtension_ = getDefaultInstance().getProofOfExtension();
      onChanged();
      return this;
    }
    /**
     * <code>string proofOfExtension = 3;</code>
     */
    public Builder setProofOfExtensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      proofOfExtension_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:decryptiondevice.DecryptionRequest)
  }

  // @@protoc_insertion_point(class_scope:decryptiondevice.DecryptionRequest)
  private static final io.grpc.decryptiondevice.DecryptionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.decryptiondevice.DecryptionRequest();
  }

  public static io.grpc.decryptiondevice.DecryptionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DecryptionRequest>
      PARSER = new com.google.protobuf.AbstractParser<DecryptionRequest>() {
    public DecryptionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DecryptionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DecryptionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DecryptionRequest> getParserForType() {
    return PARSER;
  }

  public io.grpc.decryptiondevice.DecryptionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

