// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/DeviceRPC/decryptiondevice.proto

package io.grpc.decryptiondevice;

public interface PublicKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:decryptiondevice.PublicKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes nonce = 1;</code>
   */
  com.google.protobuf.ByteString getNonce();
}
