// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/DeviceRPC/decryptiondevice.proto

package io.grpc.decryptiondevice;

/**
 * <pre>
 * Attestation Quote, containing the public key
 * </pre>
 *
 * Protobuf type {@code decryptiondevice.Quote}
 */
public  final class Quote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:decryptiondevice.Quote)
    QuoteOrBuilder {
  // Use Quote.newBuilder() to construct.
  private Quote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Quote() {
    quote_ = "";
    rSAEncryptionKey_ = com.google.protobuf.ByteString.EMPTY;
    rSAVerificationKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Quote(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            quote_ = s;
            break;
          }
          case 18: {

            rSAEncryptionKey_ = input.readBytes();
            break;
          }
          case 26: {

            rSAVerificationKey_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_Quote_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_Quote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.decryptiondevice.Quote.class, io.grpc.decryptiondevice.Quote.Builder.class);
  }

  public static final int QUOTE_FIELD_NUMBER = 1;
  private volatile java.lang.Object quote_;
  /**
   * <pre>
   *some format.. to be defined later
   * </pre>
   *
   * <code>string quote = 1;</code>
   */
  public java.lang.String getQuote() {
    java.lang.Object ref = quote_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quote_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *some format.. to be defined later
   * </pre>
   *
   * <code>string quote = 1;</code>
   */
  public com.google.protobuf.ByteString
      getQuoteBytes() {
    java.lang.Object ref = quote_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quote_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RSA_ENCRYPTIONKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString rSAEncryptionKey_;
  /**
   * <pre>
   *PEM formatted key 
   * </pre>
   *
   * <code>bytes RSA_EncryptionKey = 2;</code>
   */
  public com.google.protobuf.ByteString getRSAEncryptionKey() {
    return rSAEncryptionKey_;
  }

  public static final int RSA_VERIFICATIONKEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString rSAVerificationKey_;
  /**
   * <code>bytes RSA_VerificationKey = 3;</code>
   */
  public com.google.protobuf.ByteString getRSAVerificationKey() {
    return rSAVerificationKey_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getQuoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, quote_);
    }
    if (!rSAEncryptionKey_.isEmpty()) {
      output.writeBytes(2, rSAEncryptionKey_);
    }
    if (!rSAVerificationKey_.isEmpty()) {
      output.writeBytes(3, rSAVerificationKey_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getQuoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, quote_);
    }
    if (!rSAEncryptionKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, rSAEncryptionKey_);
    }
    if (!rSAVerificationKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, rSAVerificationKey_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.decryptiondevice.Quote)) {
      return super.equals(obj);
    }
    io.grpc.decryptiondevice.Quote other = (io.grpc.decryptiondevice.Quote) obj;

    boolean result = true;
    result = result && getQuote()
        .equals(other.getQuote());
    result = result && getRSAEncryptionKey()
        .equals(other.getRSAEncryptionKey());
    result = result && getRSAVerificationKey()
        .equals(other.getRSAVerificationKey());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUOTE_FIELD_NUMBER;
    hash = (53 * hash) + getQuote().hashCode();
    hash = (37 * hash) + RSA_ENCRYPTIONKEY_FIELD_NUMBER;
    hash = (53 * hash) + getRSAEncryptionKey().hashCode();
    hash = (37 * hash) + RSA_VERIFICATIONKEY_FIELD_NUMBER;
    hash = (53 * hash) + getRSAVerificationKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.decryptiondevice.Quote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.Quote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.Quote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.decryptiondevice.Quote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.decryptiondevice.Quote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Attestation Quote, containing the public key
   * </pre>
   *
   * Protobuf type {@code decryptiondevice.Quote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:decryptiondevice.Quote)
      io.grpc.decryptiondevice.QuoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_Quote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_Quote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.decryptiondevice.Quote.class, io.grpc.decryptiondevice.Quote.Builder.class);
    }

    // Construct using io.grpc.decryptiondevice.Quote.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      quote_ = "";

      rSAEncryptionKey_ = com.google.protobuf.ByteString.EMPTY;

      rSAVerificationKey_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.decryptiondevice.DecryptionDeviceProto.internal_static_decryptiondevice_Quote_descriptor;
    }

    public io.grpc.decryptiondevice.Quote getDefaultInstanceForType() {
      return io.grpc.decryptiondevice.Quote.getDefaultInstance();
    }

    public io.grpc.decryptiondevice.Quote build() {
      io.grpc.decryptiondevice.Quote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.decryptiondevice.Quote buildPartial() {
      io.grpc.decryptiondevice.Quote result = new io.grpc.decryptiondevice.Quote(this);
      result.quote_ = quote_;
      result.rSAEncryptionKey_ = rSAEncryptionKey_;
      result.rSAVerificationKey_ = rSAVerificationKey_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.decryptiondevice.Quote) {
        return mergeFrom((io.grpc.decryptiondevice.Quote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.decryptiondevice.Quote other) {
      if (other == io.grpc.decryptiondevice.Quote.getDefaultInstance()) return this;
      if (!other.getQuote().isEmpty()) {
        quote_ = other.quote_;
        onChanged();
      }
      if (other.getRSAEncryptionKey() != com.google.protobuf.ByteString.EMPTY) {
        setRSAEncryptionKey(other.getRSAEncryptionKey());
      }
      if (other.getRSAVerificationKey() != com.google.protobuf.ByteString.EMPTY) {
        setRSAVerificationKey(other.getRSAVerificationKey());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.decryptiondevice.Quote parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.decryptiondevice.Quote) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object quote_ = "";
    /**
     * <pre>
     *some format.. to be defined later
     * </pre>
     *
     * <code>string quote = 1;</code>
     */
    public java.lang.String getQuote() {
      java.lang.Object ref = quote_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quote_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *some format.. to be defined later
     * </pre>
     *
     * <code>string quote = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQuoteBytes() {
      java.lang.Object ref = quote_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *some format.. to be defined later
     * </pre>
     *
     * <code>string quote = 1;</code>
     */
    public Builder setQuote(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quote_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *some format.. to be defined later
     * </pre>
     *
     * <code>string quote = 1;</code>
     */
    public Builder clearQuote() {
      
      quote_ = getDefaultInstance().getQuote();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *some format.. to be defined later
     * </pre>
     *
     * <code>string quote = 1;</code>
     */
    public Builder setQuoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quote_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rSAEncryptionKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *PEM formatted key 
     * </pre>
     *
     * <code>bytes RSA_EncryptionKey = 2;</code>
     */
    public com.google.protobuf.ByteString getRSAEncryptionKey() {
      return rSAEncryptionKey_;
    }
    /**
     * <pre>
     *PEM formatted key 
     * </pre>
     *
     * <code>bytes RSA_EncryptionKey = 2;</code>
     */
    public Builder setRSAEncryptionKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rSAEncryptionKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *PEM formatted key 
     * </pre>
     *
     * <code>bytes RSA_EncryptionKey = 2;</code>
     */
    public Builder clearRSAEncryptionKey() {
      
      rSAEncryptionKey_ = getDefaultInstance().getRSAEncryptionKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rSAVerificationKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes RSA_VerificationKey = 3;</code>
     */
    public com.google.protobuf.ByteString getRSAVerificationKey() {
      return rSAVerificationKey_;
    }
    /**
     * <code>bytes RSA_VerificationKey = 3;</code>
     */
    public Builder setRSAVerificationKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rSAVerificationKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes RSA_VerificationKey = 3;</code>
     */
    public Builder clearRSAVerificationKey() {
      
      rSAVerificationKey_ = getDefaultInstance().getRSAVerificationKey();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:decryptiondevice.Quote)
  }

  // @@protoc_insertion_point(class_scope:decryptiondevice.Quote)
  private static final io.grpc.decryptiondevice.Quote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.decryptiondevice.Quote();
  }

  public static io.grpc.decryptiondevice.Quote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Quote>
      PARSER = new com.google.protobuf.AbstractParser<Quote>() {
    public Quote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Quote(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Quote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Quote> getParserForType() {
    return PARSER;
  }

  public io.grpc.decryptiondevice.Quote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

