// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/DeviceRPC/decryptiondevice.proto

package io.grpc.decryptiondevice;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:decryptiondevice.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes plaintext = 1;</code>
   */
  com.google.protobuf.ByteString getPlaintext();
}
