// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/DeviceRPC/decryptiondevice.proto

package io.grpc.decryptiondevice;

public interface RootTreeHashOrBuilder extends
    // @@protoc_insertion_point(interface_extends:decryptiondevice.RootTreeHash)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes rth = 1;</code>
   */
  com.google.protobuf.ByteString getRth();

  /**
   * <code>bytes nonce = 2;</code>
   */
  com.google.protobuf.ByteString getNonce();

  /**
   * <code>bytes sig = 3;</code>
   */
  com.google.protobuf.ByteString getSig();
}
